apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k2
  namespace: k2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Mi"
  volumeName:
  storageClassName: nfs-csi